### ISSUE TITLE
Using pandas DataFrame.append() method is deprecated (FutureWarning)

### ISSUE THREAD

**Issue by bonastreyair** [bes-dev/mean_average_precision#21]
Many logs appear with lasts pandas version 1.4.

```python
  self.match_table[c] = self.match_table[c].append(match_table)
```

/usr/local/lib/python3.8/dist-packages/mean_average_precision/mean_average_precision_2d.py:63: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

https://pandas.pydata.org/docs/whatsnew/v1.4.0.html#deprecated-frame-append-and-series-append

**Comment by sdberardinelli** [comment]
If you want, you can edit line 63 in mean_average_precision_2d.py.

`self.match_table[c] = self.match_table[c].append(match_table)`

to

`self.match_table[c] = pd.concat([self.match_table[c], match_table])`

Keep in mind, this is not an official solution.

**Comment by jnccd** [comment]
Getting a pandas error similar to this in the newest package version now
```
['map_2d']
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\nikla\miniconda3\envs\ptf\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\nikla\miniconda3\envs\ptf\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nikla\miniconda3\envs\ptf\lib\site-packages\mean_average_precision\multiprocessing.py", line 117, in _proc_loop
    metric_fn.add(preds, gt)
  File "<string>", line 2, in add
  File "C:\Users\nikla\miniconda3\envs\ptf\lib\multiprocessing\managers.py", line 825, in _callmethod
    raise convert_to_error(kind, result)
AttributeError: 'DataFrame' object has no attribute 'append'
```

**Comment by jnccd** [comment]
Without multiprocessing (which crashes for me in the README example now) it looks like this 
```
['map_2d']
Traceback (most recent call last):
  File "D:\Git\crystal-marker-detection\prototype-pytorch\test_map_package.py", line 34, in <module>
    metric_fn.add(preds, gt)
  File "C:\Users\nikla\miniconda3\envs\ptf\lib\site-packages\mean_average_precision\adapter.py", line 48, in add
    return self.metric_fn.add(preds, gt)
  File "C:\Users\nikla\miniconda3\envs\ptf\lib\site-packages\mean_average_precision\mean_average_precision_2d.py", line 63, in add
    self.match_table[c] = self.match_table[c].append(match_table)
  File "C:\Users\nikla\miniconda3\envs\ptf\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
```

**Comment by kqf** [comment]
@bes-dev Thanks a lot for the library, it saves a lot of time. Could you please upload the latest version to pypi (PR #22) please?

**Comment by bes-dev** [comment]
@kqf thanks for your interest to this project! I uploaded latest version of the library to pypi. Please, check it.

**Comment by kqf** [comment]
@bes-dev Worked like a charm. Many thanks!
